# Different colors in text

GREEN="\033[0;32m"
RED="\033[0;31m"
YELLOW="\033[0;33m"
BLUE="\033[0;34m"
MAGENTA="\033[0;35m"
CYAN="\033[0;36m"
NC="\033[0m" # No Colour

echo ""
echo -e "${NC}This line contains no color"
echo ""
echo ""
echo -e "${GREEN}This line is Green"
echo ""
echo ""
echo -e "${RED}This line is Red"
echo ""
echo ""
echo -e "${YELLOW}This line is Yelow"
echo ""
echo ""
echo -e "${BLUE}This line is Blue"
echo ""
echo ""
echo -e "${MAGENTA}This line is Magenta"
echo ""
echo ""
echo -e "${CYAN}This line is Cyan"



echo ""
echo ""
echo -e "This word is ${YELLOW}Yellow, ${GREEN}Green, ${BLUE}Blue, ${MAGENTA}Magenta, ${CYAN}Cyan, ${RED}Red"
echo ""
echo ""
echo -e "${YELLOW}This line is yellow, ${NC}and this has no colors"
echo ""